site_name: Scott CJX
site_url: https://scottcjx.com
theme:
  name: material
  features:
    - content.tabs.link

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: README.md
  - Help: help.md
